services:
  db:
    image: mysql:8.4
    container_name: db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  server:
    build: .
    image: biblioteca_app
    container_name: server
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy

volumes:
  data: