version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  server:
    build: .
    image: biblioteca_app
    container_name: server
    restart: always
    ports:
      - "${PORT}:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  data: