# Generated by Django 4.2.13 on 2024-05-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='existencias',
            field=models.PositiveIntegerField(),
        ),
    ]
