# Generated by Django 4.2.13 on 2024-05-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='existencias',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='codigo_autor',
            field=models.ForeignKey(db_column='codigo_autor', on_delete=models.deletion.CASCADE, to='biblioteca.autor'),
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='codigo_autor',
            new_name='autor',
        ),
        migrations.AlterField(
            model_name='libro',
            name='codigo_editorial',
            field=models.ForeignKey(db_column='codigo_editorial', on_delete=models.deletion.CASCADE, to='biblioteca.editorial'),
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='codigo_editorial',
            new_name='editorial',
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_genero',
            field=models.ForeignKey(db_column='id_genero', on_delete=models.deletion.CASCADE, to='biblioteca.genero'),
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='id_genero',
            new_name='genero',
        ),
    ]
